-- Down migration for 20260902082836_org_settings.
-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).
-- Review before use: a diff renders a rename as DROP + ADD, which loses data.

-- DropTable
DROP TABLE "public"."org_settings";
