-- Down migration for 20260901215034_add_idempotency_records.
-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).
-- Review before use: a diff renders a rename as DROP + ADD, which loses data.

-- DropTable
DROP TABLE "public"."idempotency_records";
