// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Required by `prisma migrate diff --from-migrations`, which the migration
    // drift check runs: Prisma replays the migration history into a throwaway
    // database and compares the result with the schema.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
