-- Down migration for 20260902055959_better_auth.
-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).
-- Review before use: a diff renders a rename as DROP + ADD, which loses data.

-- DropForeignKey
ALTER TABLE "public"."account" DROP CONSTRAINT "account_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."invitation" DROP CONSTRAINT "invitation_inviter_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."invitation" DROP CONSTRAINT "invitation_organization_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."member" DROP CONSTRAINT "member_organization_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."member" DROP CONSTRAINT "member_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."organizationRole" DROP CONSTRAINT "organizationRole_organization_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."session" DROP CONSTRAINT "session_user_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."twoFactor" DROP CONSTRAINT "twoFactor_user_id_fkey";

-- DropTable
DROP TABLE "public"."account";

-- DropTable
DROP TABLE "public"."apikey";

-- DropTable
DROP TABLE "public"."invitation";

-- DropTable
DROP TABLE "public"."member";

-- DropTable
DROP TABLE "public"."organization";

-- DropTable
DROP TABLE "public"."organizationRole";

-- DropTable
DROP TABLE "public"."session";

-- DropTable
DROP TABLE "public"."twoFactor";

-- DropTable
DROP TABLE "public"."user";

-- DropTable
DROP TABLE "public"."verification";
