import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  MIGRATIONS_DIR,
  listMigrations,
  stageHistory,
} from './migration-history.js';

/**
 * Generates `down.sql` for one migration, the way the Prisma docs describe
 * ("Generating down migrations"): diff the migration history *with* the
 * migration against the history *without* it, in reverse.
 *
 * `prisma migrate diff` only knows how to diff whole directories, so the two
 * histories are staged as temporary directories. Nothing is written by hand
 * here; renames still need a human afterwards, because a diff renders them as
 * DROP + ADD.
 *
 *   pnpm nx run core-server-data-access-db:prisma-down --name=<migration>
 */
function main(): void {
  const name = readNameArgument();
  const migrations = listMigrations();

  const index = migrations.indexOf(name);
  if (index === -1) {
    throw new Error(`No migration named "${name}" in ${MIGRATIONS_DIR}`);
  }

  const staging = mkdtempSync(join(tmpdir(), 'prisma-down-'));
  try {
    const withMigration = stageHistory(
      join(staging, 'with'),
      migrations.slice(0, index + 1),
    );
    const withoutMigration = stageHistory(
      join(staging, 'without'),
      migrations.slice(0, index),
    );

    const sql = execFileSync(
      'pnpm',
      [
        'exec',
        'prisma',
        'migrate',
        'diff',
        '--from-migrations',
        withMigration,
        ...(index === 0
          ? ['--to-empty']
          : ['--to-migrations', withoutMigration]),
        '--script',
      ],
      {
        encoding: 'utf8',
        shell: process.platform === 'win32',
        stdio: ['ignore', 'pipe', 'inherit'],
      },
    );

    const target = join(MIGRATIONS_DIR, name, 'down.sql');
    writeFileSync(target, `${header(name)}\n${sql.trimEnd()}\n`);
    console.log(`wrote ${target}`);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

function readNameArgument(): string {
  const raw = process.argv.find((arg) => arg.startsWith('--name='));
  const name = raw?.slice('--name='.length);
  if (!name) {
    throw new Error('Usage: prisma-down --name=<migration directory name>');
  }
  return name;
}

function header(name: string): string {
  return [
    `-- Down migration for ${name}.`,
    '-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).',
    '-- Review before use: a diff renders a rename as DROP + ADD, which loses data.',
    '',
  ].join('\n');
}

main();
