-- Down migration for 20260901203826_init_demo_item.
-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).
-- Review before use: a diff renders a rename as DROP + ADD, which loses data.

-- DropTable
DROP TABLE "public"."demo_items";
