-- Down migration for 20260902071727_tenant_reference_tables.
-- Generated by tools/prisma-down.ts (prisma migrate diff, reversed).
-- Review before use: a diff renders a rename as DROP + ADD, which loses data.

-- DropTable
DROP TABLE "public"."bookmarks";

-- DropTable
DROP TABLE "public"."notes";
