import { formatFiles, joinPathFragments, type Tree } from '@nx/devkit';

import type { ProductScopeGeneratorSchema } from './schema.js';

/**
 * Adding a product scope means touching several places that must stay in sync:
 * the apps, their tags, and the boundary rules. Rather than scaffolding apps we
 * cannot configure blindly, this generator writes the exact, ordered steps for
 * the new scope so nothing is done from memory.
 */
async function productScopeGenerator(
  tree: Tree,
  options: ProductScopeGeneratorSchema,
) {
  const { name } = options;

  const checklist = `# Adding the "${name}" product scope

Generated by \`nx g @workspace/workspace-plugin:product-scope --name=${name}\`.
Run the steps in order; each one is a CLI command, nothing is edited by hand
except the boundary rule.

## 1. Applications

\`\`\`bash
pnpm nx g @nx/nest:application apps/${name}/api \\
  --name=${name}-api --linter=eslint --unitTestRunner=none \\
  --e2eTestRunner=none --useProjectJson=true --strict \\
  --tags="scope:${name},platform:node,type:app"
pnpm nx g @nx/vitest:configuration --project=${name}-api

pnpm nx g @nx/next:application apps/${name}/web \\
  --name=${name}-web --style=css --appDir --src --linter=eslint \\
  --unitTestRunner=none --e2eTestRunner=playwright --useProjectJson=true \\
  --tags="scope:${name},platform:web,type:app"
\`\`\`

After generating the Nest app, switch it to the Fastify adapter the way
\`apps/core/api/src/main.ts\` does, and copy the webpack \`IgnorePlugin\`
configuration that keeps unused Nest optional integrations out of the bundle.

## 2. Feature libraries

\`\`\`bash
pnpm nx g @workspace/workspace-plugin:feature-lib --name=<feature> --scope=${name} --platform=node
pnpm nx g @workspace/workspace-plugin:feature-lib --name=<feature> --scope=${name} --platform=web
\`\`\`

## 3. Boundary rule

Add the scope to \`eslint.boundaries.mjs\` (the single definition of the
dependency matrix — the root config and every project config import it):

\`\`\`js
{
  sourceTag: 'scope:${name}',
  onlyDependOnLibsWithTags: ['scope:${name}', 'scope:shared'],
},
\`\`\`

## 4. Verify

\`\`\`bash
pnpm verify
\`\`\`
`;

  tree.write(joinPathFragments('docs', `scope-${name}-checklist.md`), checklist);

  await formatFiles(tree);
}

export default productScopeGenerator;
